version: '3.8'

services:
  web:
    build: .
    container_name: tapo-control-web
    env_file:
      - .env
    ports:
      - "8000:5000"
    volumes:
      - ./logs:/app/logs
    # IoT 디바이스 접근이 필요하면 host mode 사용 가능
    # network_mode: "host"
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: tapo-control-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped

networks:
  default:
    driver: bridge
