# =============================================================================
# DOCKER COMPOSE CONFIGURATION FOR SYNOLOGY DEPLOYMENT
# =============================================================================
# SSL termination is handled by Synology reverse proxy
# This configuration only exposes HTTP ports

services:
  # Web Application
  web:
    build: .
    container_name: tapo-control-web
    env_file: .env
    ports:
      - "5011:5011"  # Changed from 5003 to 5011
    volumes:
      - ./logs:/app/logs
      - ./users.db:/app/users.db:rw  # Mount with read-write permissions
      - ./data:/app/data  # Keep data directory for future use
    restart: unless-stopped
    networks:
      - tapo-net

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: tapo-control-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/var/www/static:ro
    ports:
      - "${NGINX_HTTP_PORT:-84}:80"    # HTTP only - Synology handles HTTPS
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - tapo-net

  # Development Database Manager (dev only)
  adminer:
    image: adminer
    container_name: tapo-control-adminer
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    profiles: ["dev"]
    networks:
      - tapo-net

# ─── NETWORKS ─────────────────────────────────────────────────────────────────
networks:
  tapo-net:
    driver: bridge
