

services:
  web:
    build: .
    container_name: tapo-control-web
    env_file:
      - .env
    ports:
      - "5005:5005"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - tapo-net

  nginx:
    image: nginx:stable
    container_name: tapo-control-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - tapo-net

networks:
  tapo-net:
    driver: bridge
